AllCops:
  TargetRubyVersion: 2.5.5
  Exclude:
    - 'bin/**/*'
    - 'db/seeds/'
    - 'db/views/'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - namespace
    - task
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'Gemfile'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/copiers/default_settings.rb'

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
    - 'spec/**/*'

Style/MethodMissingSuper:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'app/models/ability.rb'
